# Generated by Django 4.2.6 on 2023-10-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_delete_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.webp', upload_to='profile_pics'),
        ),
    ]
